# ------------------------------------------------------------------------------------------------------

# Version 1.0.0
# Created by Guacamoleboy
# Last updated: 30/05-2026

# FILE PURPOSE
#   - Nginx configuration for MoodMap Frontend Application.
#   - Serves static build files and redirects to the initial index.html page.
#   - Enables Client-Side React Router aswell.

# ------------------------------------------------------------------------------------------------------

server {
  listen 80;

  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri $uri/ /index.html;
  }
}